at_exit で登録したプロセス終了時に実行するブロック内で例外発生と rescue 節での
捕捉を行うと errinfo が上書きされてしまう不具合を修正しています。うーんなるほど
。そんなことするなよ……と思わなくもなかったのですが、終了時に止まる原因になっ
た例外を使ってなにかしたいというのは確かにありそう。 [ruby-core:75038] [Bug #
12302]
