Array#select! や Array#reject! などの破壊的メソッドでブロック内での例外発生時の ensure 節に相当する処理で戻り値とする配列に対して再度 rb_ary_modify() を呼ぶようにしています。メソッドの入口でも呼んでますが、ブロック内で freeze される場合を考慮しているようです。 [ruby-core:102955] [Bug #17736]
