class 文で既に定義済みの Class を再度 open する時に継承元として Class じゃないものを渡したりした時の例外メッセージを修正しています。 [ruby-dev:50527] [Bug #14726]
