test/ruby/test_exception.rb のテストで Tempfile.new にブロック付きで呼び出しし
ていて、Tempfile.new はブロックを受け付けないので実はブロック内の処理が実行され
ていなくてテストになっていなかったので Tempfile.open を使うように修正しています
。なんかこのテスト書いたのわたしのような気がします。うう、すみません。
