TracePoint のイベントフック内で例外が発生した時に呼び元から例外が外に伝播するよ
うにしています。 r38293 で例外はイベントフック内から漏れないようにしていました
が、例外が発生していたら TH_JUMP_TAG() を呼んで再発生させるように戻しています。
そのかわり return のイベントフックで例外が発生すると無限ループ?が発生していたの
に対応するためか、vm_exec() の VM メインループで rb_thread_t::tag のスタックを
余分に積んで例外処理時に pop するようにしています。一箇所 TH_POP_TAG2() を削除
しているのはいいんでしょうか。あと rb_thread_t::tag のスタック(というか実体はリ
ンクリストですけど)を1つ余分に積んでいるのに正常に処理が進んだ時に pop しなくて
いいんでしょうか。
